### ISSUE TITLE
Compatibility with React 0.14

### ISSUE THREAD

**Issue by einarq** [clayallsopp/react.backbone#47]
React.Backbone is currently using this.getDOMNode, this is deprecated in React 0.14.
Will React.Backbone be updated to get rid of this warning?

**Comment by markijbema** [comment]
If this is important to you I would suggest making a PR. I'm currently not using this project, but are reviewing (not sure about @clayallsopp , but it might well be that this is no issue to him at the moment either).

The code is small enough that it shouldn't be too hard to fix.

**Comment by einarq** [comment]
So i guess this is not really maintained anymore? Connecting a model directly to a react component is perhaps not considered very good practice anymore? Still useful in some cases though imo.

**Comment by markijbema** [comment]
I don't think there's much work going into this project, but since the scope is well-defined that's not needed either imo. I think this is a good example of a project that's "done". I mean, upgrades need to be supported, but I don't think there's a need to add more functionality.

Personally, I've only used this during a transition from backbone to react, and I don't think Backbone maps cleanly to React, so imo it's not a perfect solution. Otoh, I know people who use it and are happy to keep using it.

I wouldn't say it's not maintained either, both @clayallsopp and I participate in issues and PRs, but actually fixing the code myself is no priority for me at least, more so because currently I'm not using react, so I wouldn't implement it as well as someone who does.

**Comment by clayallsopp** [comment]
Originally fixed by #48, code removed in #51, so warning is gone
