### ISSUE TITLE
Use-case for `el()`

### ISSUE THREAD

**Issue by SpaceK33z** [clayallsopp/react.backbone#50]
What is the use-case for the [`el()`](https://github.com/clayallsopp/react.backbone/blob/master/react.backbone.js#L126) method? I'm wondering because it is not tested, not documented and because of this the package does not work with react-native (it requires `react-dom`).

**Comment by clayallsopp** [comment]
Good question, pretty awesome that you'd like to use this with react-native. It's been there since the first commit (c15403e1bd66d7ad53931166dad472164ed0df17), probably an artifact of how it was used at the time.

I'm fine with removing it - would welcome a PR that removes it and bumps react.backbone's version to 0.8.0 :)

**Comment by clayallsopp** [comment]
closed by #51
